// Create your HTML Page via DOM Methods here!
var tag = document.createElement("h1");
var h2Tag = document.createElement("h2");
var olTag = document.createElement("ol");
var liTag = document.createElement("li");
var li2Tag = document.createElement("li");
var li3Tag = document.createElement("li");
var imgTag = document.createElement("img");
var pTag = document.createElement("p");
tag.textContent = "Hello JavaScript generation!";
tag.style.textAlign = "center";
document.body.appendChild(tag);
h2Tag.textContent = "This page is completely built with javascript!";
h2Tag.style.textAlign = "center";
document.body.appendChild(h2Tag);
imgTag.setAttribute("style","display: block; margin-left: auto; margin-right: auto;");
imgTag.setAttribute("src", "https://placekitten.com/200/200");
document.body.appendChild(imgTag);
pTag.textContent = "This is a placeholder image, isn't it amazing?";
pTag.style.textAlign = "center";
document.body.appendChild(pTag);
olTag.setAttribute("style","background-image: repeating-linear-gradient(red, white, blue);");
olTag.textContent = "List of my favourite past times";
document.body.appendChild(olTag);
liTag.textContent = "Coding";
document.body.lastElementChild.appendChild(liTag);
li2Tag.textContent = "Gaming";
document.body.lastElementChild.appendChild(li2Tag);
li3Tag.textContent = "Browsing";
document.body.lastElementChild.appendChild(li3Tag);